# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
        - image: circleci/php:7.1-apache-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install PHP php-xsl
          command: sudo apt-get install php-xml

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run and build tests!
      - run: vendor/bin/phpunit tests/
      - run: vendor/bin/phpcs --report=checkstyle --report-file=build/logs/checkstyle.xml --standard=PSR2 src/
      - run: vendor/bin/phpmd src/ html cleancode,codesize,controversial,design,unusedcode --reportfile build/logs/pmd.html
      - run: vendor/bin/phpcpd --log-pmd build/logs/pmd-cpd.xml src/
      - run: vendor/bin/phploc src/ > build/logs/phploc.html
      - run: vendor/bin/phpdox
