# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
        - image: meezaan/php-apache-7.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
        - image: meezaan/perconadb5.7
    working_directory: /app

    steps:
      - run: cd /
      - run: rm -rf /app
      - run: git clone https://github.com/meezaan/microservice-template.git app
      - run: cd app
      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run and build tests!
      - run: vendor/bin/phpunit tests/
      - run: vendor/bin/phpcs --report=checkstyle --report-file=build/logs/checkstyle.xml --standard=PSR2 src/
      - run: vendor/bin/phpmd src/ html cleancode,codesize,controversial,design,unusedcode --reportfile build/logs/pmd.html
      - run: vendor/bin/phpcpd --log-pmd build/logs/pmd-cpd.xml src/
      - run: vendor/bin/phploc src/ > build/logs/phploc.html
      - run: vendor/bin/phpdox
