connections:
#    memcache:
#        host: memcached
#        port: 11211

slim:
  settings:
    display_error_details: true # use for debugging only
    add_content_length: true # Adds content length header to all responses
    template_engine: "twig"

app:
  flags:
    enable_inbenta_support_page: true
    money_banner: true
    dashboard_light: true

