<?php
/**
 * Master layout
 *
 * @author Ian.H <ian@giffgaff.co.uk>
 *
 * @var Tightenco\Collect\Support\Collection $layout
 * @var Tightenco\Collect\Support\Collection $flags
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="keywords" content="#SEO_KEYWORDS_INDEX#">
    <meta name="description" content="giffgaff the mobile network run by you. Great value goodybags packed full of minutes texts and internet. Visit us online today.">
    <meta property="og:title" content="">
    <meta property="og:description" content="">
    <meta property="og:image" content="https://www.giffgaff.com/styleguide/images/layout/giffgaff_logo_1200x630.jpg">
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no">
    <meta name="theme-color" content="#000000">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, minimum-scale=1">
    <title><?=$title?> | giffgaff</title>
    <link href="//fonts.googleapis.com/css?family=Lato:400normal,900normal&amp;subset=all" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Gochi+Hand" rel="stylesheet" type="text/css">
<!--    <link href="/styleguide/css/home.min.1.css" media="screen" rel="stylesheet" type="text/css">-->
    <link href="https://www.giffgaff.com/styleguide/css/home.min.1531327897.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/" rel="canonical">
    <link href="/favicon.ico" rel="favicon">
    <link href="/gfx/icons/iphone-icon.png" rel="apple-touch-icon">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link href="//plus.google.com/101822437399736576163" rel="publisher">

    <script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-M9K7LQ"></script><script async="" src="https://www.google-analytics.com/analytics.js"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        window.dataLayer.push({"floodlight_params":{"pixel_activity_enabled":1,"pixel_activity_name":"Homepage Pixel","pixel_activity_type":"homep018","pixel_activity_cat":"homep525"},"arm_fl":{"deviceType":"desktop","pageType":"unknown"},"responsive":0});

    </script>
    <script type="text/javascript">
        var gg = {};
        gg.controllers = {};
        gg.widgets = {};
        gg.responsiveMode = 0;
    </script>
    <?php if ($app->get('layout')):?>
        <meta name="apple-itunes-app" content="app-id=<?=$app->get('iphoneAppId')?>"/>
    <?php endif; ?>
</head>
<body>
<a href="#content" class="sr-only">Skip to content</a>
<div id="wrapper" class="wrapper wrapper-gray">
    <?php if(!$app->get('detect')->displayApp):?>
        <nav id="top-nav" class="navbar <?=$app->get('layout')->staticTopNav ? 'navbar-scroll-top' : ''?> navbar-fixed-top" role="navigation">
            <?php if ($app->get('promo')->isBlackFridayPromoOn):?>
                <div class="alert alert-notification gold">
                    <a class="goto plain"
                       href="/black-friday">
                        Black Friday is on!
                    </a>
                    <a href="#" data-dismiss="alert" class="close">×</a>
                </div>
            <?php endif;?>

            <div class="navbar-inner">
                <div class="container">
                    <a id="logo" class="brand" href="/">giffgaff homepage</a>
                    <?php if ($app->get('layout')->showNavigation):?>
                        <a id="link_menu_open_close" class="btn btn-navbar collapsed visible-phone hidden-desktop hidden-tablet" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <?php if ($flags->get('enable_inbenta_support_page')):?>
                            <span class="nav__inbenta-toggler nav__inbenta-toggler--small btn-navbar visible-phone hidden-desktop hidden-tablet"></span>
                        <?php endif;?>
                        <?php if ($app->get('displayPhone')):?>
                            <a id="icon-member-dashboard" class="pull-right icon-member-container  visible-phone hidden-desktop hidden-tablet" href="/dashboard">
                                <?php if ($app->get('userLoggedIn')):?>
                                    <img class="member-profile" width="33" height="33" src="<?php echo $this->TopNavMenu()->setProfileImage()?>">
                                <?php else:?>
                                    <i class="icon-35x35-my-giffgaff_active"></i>
                                <?php endif;?>
                            </a>
                        <?php endif;?>
                        <?php //include_once __DIR__ . '/partials/topnav.phtml' ?>
                        <div class="nav-collapse collapse visible-phone">
                            <?php /*echo $this->partial('topnav.mobile.phtml', array(
                                'navigationBanner' => $this->navigationBanner,
                            ))*/ ?>
                        </div>
                    <?php else: //echo $this->placeholder('replace-navigation'); ?>
                    <?php endif; ?>
                </div>
            </div>
        </nav>
        <?php /*if ($app->get('notifications') && $app->get('layout')->showNavigation):
            $this->partialLoop()->setObjectKey('notification');
            echo $this->partialLoop('_notification.phtml', $this->notifications);
        endif;*/ ?>
    <?php endif ?>

    <div id="content" class="content">
        <!-- Show only messages on top only if no section specific messages  --->
        <?php if (!$app->get('showSectionSpecificFlashMessages')): ?>
            <?php //include_once __DIR__ . '/styleguide-messenger.phtml'; ?>
        <?php endif; ?>
        <?php
        // The main view is rendered in here
        //echo $this->layout()->content;
        ?>
        <div id="home-page" class="span12 span-wrap sections-container">
            <?php /* --- Main column --- */ ?>
            <?php //echo $this->render("index/sections/_top_section.phtml", $this) ?>

            <?php if ($app->get('isBlackFridayPromoOn') || $app->get('isXmasPromoOn')):?>
                <?php // Blackfriday content ?>
                <?php //echo $this->render('index/partials/_index_blackfriday_xmas.phtml')?>
            <?php else:?>
                <?php // Regular homepage content ?>
                <?php //include_once __DIR__ . '/index/partials/_index_regular.phtml';?>
            <?php endif;?>
        </div>
        <?php //$this->placeholder('bottom_links')->captureStart(); ?>
        <div id="bottom_links" class="foot-wrapper">
            <div class="container" id="footer_menu">
                <div class="row-fluid">
                    <?//= t('HOME_FOOTER_LINKS') ?>
                </div>
            </div>
        </div>
        <?php //$this->placeholder('bottom_links')->captureEnd(); ?>

        <?php if (($app->get('detect')->isAndroid || $app->get('detect')->isAndroidtablet) && !$app->get('detect')->displayApp && empty($_COOKIE['android-app-banner'])): ?>
            <div id="android-banner" class="android-banner" style="display:none;">
                <a href="#" class="android-banner-close">×</a>
                <img src="//lh6.ggpht.com/oIHHWBi8Bll80ytNlTkUdDmdo-AWrpKxzwtA7wCF_w1JvmXrC5e86KsenBeR7bSUYBg=w300-rw"
                     class="open-app-icon" alt="giffgaff android"/>
                <div class="android-app-info">
                    <div class="android-app-title">my giffgaff</div>
                </div>
                <a id="androidAppLink" class="open-app-link" href="/android-app/">OPEN</a>
            </div>
        <?php endif; ?>
    </div>

    <?php if(!$app->get('detect')->displayApp): ?>
        <?php //include_once __DIR__ . '/footer.phtml';?>
    <?php endif ?>
</div>


<?php // echo $this->placeholder('gg_alert_messages'); ?>

<!-- JS Placed at the end of the document so the pages load faster -->
<script src="https://www.giffgaff.com/styleguide/js/vendor/jquery.min.1531327897.js"></script>
<script src="https://www.giffgaff.com/styleguide/js/controllers/home.min.1531327897.js"></script>
<script type="application/ld+json">
    //<!--
    { "@context" : "http://schema.org", "@type" : "WebSite", "name" : "giffgaff", "alternateName" : "giffgaff", "url" : "https://giffgaff.com"}    //-->
</script>
<?php if($flags->get('firstLoginMessage') && App::user()):?>
    <?php $firstLogin = App::usersService()->getFirstLogin();?>
    <?php if ('false' === $firstLogin):?>
        <div id="modalFirstLogin" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="modalFirstLoginLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="modalFirstLoginLabel"><?php echo th('LOGIN_MESSAGE_title'); ?></h3>
            </div>
            <div class="modal-body">
                <?= t('LOGIN_MESSAGE_text');?>
            </div>
        </div>
    <?php endif;?>
<?php endif;?>

<?php //include_once __DIR__ . '/modalbox/privacy-policy-modal.phtml'; ?>
<?php //include_once __DIR__ . '/_widgets/modal_eu_euro_zone_countries.phtml'; ?>
<?php //echo $this->iovation()->renderBlackbox(); ?>
<!-- Page generated <?=$this->currentServer;?>-->
<!-- Campaign <?php //echo $this->escape(App::session('campaign')->utm_campaign) ?> -->
<?php if ($flags->get('enable_inbenta_support_page')):?>
    <script>
        if (window['ggInbentaSearch']) {
            window['ggInbentaSearch'].injectTogglers([{
                selector: '.nav__inbenta-toggler',
                options: {
                    hoverTransition: false
                }
            }]);
        }
    </script>
<?php endif;?>
</body>
</html>
